config:
    info: 'branch master springcloud-config/config-dev.yml version=1'
datasource:
    url: jdbc:mysql://localhost:3306/springcloud?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
